module.exports = Object.freeze({
    FILE_PATH: "./src/resources/ControlTesoreriaTest.xlsx",
    HOUSE_LABEL: "CASA",
    NAME_LABEL: "NOMBRES",
    LOCAL_LABEL: "LOCALES",
    MONTH_DOUBLE_ALIQUOT_NAME: "Marzo",
    PENDINGS_REP_LABEL: "Pendings",
    TOTAL_REP_LABEL: "Total",
    DET_YEAR_LABEL: "year",
    DET_MONTH_LABEL: "month",
    DET_PENDING_LABEL: "pendingVal",
    MSG_GREETING_INIT: "Estimado condomino de ",
    MSG_GREETING_COMPL: "Reciba un cordial saludo de la directiva del Conjunto Habitacional Garden's Club.",
    MSG_GREETING_COMPL2: "A continuación se detalla los haberes pendientes que usted tiene con el conjunto:",
    MSG_GREETING_COMPL4: "Agradecemos su puntualidad en los pagos de las alicuotas, al momento usted no tiene haberes pendientes",
    MSG_GREETING_DETAIL: "A continuación se detalla los pagos que ha realizado a esta directiva:",
    MSG_DETAIL_VOID: "Usted no ha realizado pagos a esta directiva",
    MSG_IN_PENDING: "PENDIENTES",
    MSG_IN_DETAILS: "DETALLES",
    MSG_IN_WELLCOME: "Les recuerdo que soy un BOT y puedo responder a dos mensajes:",
    MSG_CUT_DATE: "\n*Fecha de corte*: ",
    SHT_STATUS_ACOUNT_NAME: "Estados_cuenta",
    SHT_ALIQUOTS_NAME: "Alicuotas",
    SHT_TELF_NAME: "TelefonosPrueba",
    //SHT_TELF_NAME: "Telefonos",
    SHT_TELF_NAME_LABEL: "NOMBRE",
    SHT_TELF_HOUSE_LABEL: "CASA",
    SHT_TELF_CELL1_LABEL: "Celular1",
    SHT_TELF_CELL2_LABEL: "Celular2",
    SHT_INC_NAME: "Det_ingresos",
    SHT_INC_DATE_LABEL: "Fecha_Ingreso",
    SHT_INC_COND_LABEL: "Condomino",
    SHT_INC_HOUSE_LABEL: "Casa",
    SHT_INC_VALUE_LABEL: "Valor",
    SHT_INC_TYPE_LABEL: "Tipo_de_ingreso",
    SHT_INC_DOC_LABEL: "Documento",
    SHT_INC_DESC_LABEL: "Descripcion",
    REP_PEND_TOTAL_LABEL: "*Total*: ",
    REP_DESC_TRANSF_TYPE_LABEL: "Transferencia"
    
});